services:
  log-server:
    build:
      context: .
      dockerfile: LogCentralizationService/Dockerfile
    ports:
      - "5000:8080" # <-- Le 8080 est crucial ici
    volumes:
      - ./logs_data:/app/logs